name = "framer-templates-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
workers_dev = true

[observability]
enabled = true

# Development Environment
[env.development]
vars = { ENVIRONMENT = "development" }

[[env.development.r2_buckets]]
binding = "TEMPLATES_BUCKET"
bucket_name = "framer-templates-dev"

[[env.development.r2_buckets]]
binding = "BACKUPS_BUCKET"
bucket_name = "framer-templates-backups"

# Staging Environment
[env.staging]
vars = { ENVIRONMENT = "staging" }

[[env.staging.r2_buckets]]
binding = "TEMPLATES_BUCKET"
bucket_name = "framer-templates-staging"

[[env.staging.r2_buckets]]
binding = "BACKUPS_BUCKET"
bucket_name = "framer-templates-backups"

# Production Environment
[env.production]
vars = { ENVIRONMENT = "production" }

[[env.production.r2_buckets]]
binding = "TEMPLATES_BUCKET"
bucket_name = "framer-templates-prod"

[[env.production.r2_buckets]]
binding = "BACKUPS_BUCKET"
bucket_name = "framer-templates-backups"

# Rate Limiting
[[unsafe.bindings]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1"
simple = { limit = 100, period = 60 }

# Analytics Engine (optional)
[[analytics_engine_datasets]]
binding = "ANALYTICS"